### ISSUE TITLE
❓[SUPPORT]:  Compile for Ivy distribution

### ISSUE THREAD

**Issue by eddiepaz** [ngxs/store#1818]
Are there any plans to support Ivy in the near future? When compiling:

Angular 13.1.3
@ngxs/store: 3.7.3

We get the message "Processing legacy "View Engine" libraries:

- @ngxs/store/internals [es2015/esm2015] (git+https://github.com/ngxs/store.git)
- @ngxs/store [es2015/esm2015] (git+https://github.com/ngxs/store.git)
- @ngxs/devtools-plugin [es2015/esm2015] (git+https://github.com/ngxs/store.git)
Encourage the library authors to publish an Ivy distribution.

Much appreciated!

**Comment by akialapiha** [comment]
Any updates on this?

**Comment by wiesnery** [comment]
Would like to see this moving as well. I think it is nice to support old Angular versions, but supporting ones, which are eol may be disputable.
You can see the list of currently supported versions [here](https://angular.io/guide/releases#support-policy-and-schedule) and it states that v12 is the oldest supported version by the time posting this.

In addition to that, it might be a good sign for an intact framework to support current technologies. Especially, when new projects are in the process of framework selection, I would love to see ngxs in a more attractive position.

**Comment by tfechtner** [comment]
Any updates on this please?

**Comment by markwhitfeld** [comment]
This is still WIP, but very close to an RC release.
I will post here first to get feedback on the RC 😉

**Comment by kodze** [comment]
Hello :) 

Any update?

Thanks for your work!!

**Comment by Sieabah** [comment]
@markwhitfeld Hopefully ngxs has a release that is ivy, because I believe Angular15 would make this library unusable since they're removing support for libraries which aren't built for ivy.

I'm not sure if publishing both versions within the same major version makes much sense since 3.7.x has been the latest version for almost 2 years. It's nice goal, but seems almost unnecessary. If it's complicated to support both in the same version you can bump the major version and make it clear 4.x is the ivy build.

**Comment by paulstelzer** [comment]
Angular 15 is out now and if you are using the experimental esbuild the app is not running because of ngxs. Can we expect an update soon?

**Comment by markwhitfeld** [comment]
We will be compiling for Ivy from the next release (v3.8). This is planned
for next week.

**Comment by luishcastroc** [comment]
is this still planned for this week? the majority of my stuff seems to be working inside angular 15 but well want to be sure, thanks for the great job.

**Comment by markwhitfeld** [comment]
The PR is in progress, so we will see how it goes ;-)

**Comment by luishcastroc** [comment]
> `3.7.5` seemed to be building ES2020. I see `3.7.6` just dropped but it is building ES2015.
> 
> ```
> ⠙ Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:
> - @ngxs/store/internals [es2015/esm2015] (git+https://github.com/ngxs/store.git)
> - @ngxs/store [es2015/esm2015] (git+https://github.com/ngxs/store.git)
> - @ngxs/store/operators [es2015/esm2015] (git+https://github.com/ngxs/store.git)
> - @ngxs/router-plugin [es2015/esm2015] (git+https://github.com/ngxs/store.git)
> - @ngxs/storage-plugin [es2015/esm2015] (git+https://github.com/ngxs/store.git)
> - @ngxs/devtools-plugin [es2015/esm2015] (git+https://github.com/ngxs/store.git)
> ```

yeah the PR is not merged yet so that's not the one

**Comment by arturovt** [comment]
We've merged the commit that switched to partial compilation format and doesn't require `ngcc`. It's available under `3.7.6-dev.master-dcdd391`. The package is built using Angular 12 since it's the initial version supporting Angular package format and it's compatible with all of the next versions. You can install it and test it out:
```sh
$ npm install @ngxs/store@3.7.6-dev.master-dcdd391
```

**Comment by luishcastroc** [comment]
> We've merged the commit that switched to partial compilation format and doesn't require `ngcc`. It's available under `3.7.6-dev.master-dcdd391`. The package is built using Angular 12 since it's the initial version supporting Angular package format and it's compatible with all of the next versions. You can install it and test it out:
> 
> ```shell
> $ npm install @ngxs/store@3.7.6-dev.master-dcdd391
> ```
> 
> We're planning this to be available in 3.8.0 version.

thanks for the hard work, are there dev.master versions as well for the router and other plugins?

**Comment by arturovt** [comment]
Yes, they are published with the same version.

**Comment by markwhitfeld** [comment]
> We've merged the commit that switched to partial compilation format and doesn't require `ngcc`. It's available under `3.7.6-dev.master-dcdd391`. The package is built using Angular 12 since it's the initial version supporting Angular package format and it's compatible with all of the next versions. You can install it and test it out:
> 
> ```shell
> $ npm install @ngxs/store@3.7.6-dev.master-dcdd391
> ```
> 
> We're planning this to be available in 3.8.0 version.

Can I ask if some volunteers from this channel could attempt an upgrade in their codebases and give feedback on the result?
We would like to cut the 3.8.0 release soon, and this feedback would be very valuable.
Testing out the latest dev version would be the best:
```
npm install @ngxs/store@dev
```
You would need to do the same for any ngxs plugins that you use.

**Comment by luishcastroc** [comment]
I Can give it a try, what kind of testing are you looking for?

**Comment by markwhitfeld** [comment]
Thanks @luishcastroc. I would say something like the following:
Install the new version, build your app, run your tests, any other kind of sanity checks that you may usually do.
In the upgrade you may need to fix some types if you use state operators, because the type checking and inference have been improved.
If you need to do these type fixes, it would be great if you could describe the change you had to make 🙏.

**Comment by Sieabah** [comment]
I can give this a shot later tonight

**Comment by me4502** [comment]
I've just ran a test with this version and everything seems to be working well. Only using devtools in terms of plugins though so can't comment on the other plugins.

**Comment by Sieabah** [comment]
Building within node:16 docker container, angular 14 (been holding off on angular 15 until this was released)

    "@ngxs/router-plugin": "^3.7.6-dev.master-5f9405c",
    "@ngxs/store": "^3.7.6-dev.master-5f9405c",
    "@ngxs/devtools-plugin": "^3.7.6-dev.master-5f9405c",

I upgraded my project to angular 15 with the same versions listed above and also ran into no issues

**Comment by paulstelzer** [comment]
Also updated my project (using store, devtools and storage) and everything is working like before. Great job und esbuild is working now too

**Comment by kodze** [comment]
Hello! 

Same here, no issues with the version! (node:14 + angular 14)

**Comment by luishcastroc** [comment]
haven't seen issues with Angular 15 my angular 15 standalone application

**Comment by msalzig** [comment]
Same to me. No issues with angular 15 application.

**Comment by ice-blaze** [comment]
Using angular `14.2.0` and stumbled to this issue only for the runtime (unit tests and building work well) 
![image](https://user-images.githubusercontent.com/3356843/208397519-98d99021-3587-43d4-a9af-70368a534160.png)
Versions (previous was `3.75`) :
```
"@ngxs/devtools-plugin": "^3.7.6-dev.master-5f9405c",
"@ngxs/form-plugin": "^3.7.6-dev.master-5f9405c",
"@ngxs/store": "^3.7.6-dev.master-5f9405c",
```
I didn't had time to invest more into the error can't confirm it's  NGXS :) 

(I have 4 projects in my mono repo the stack trace is a little bit different on other projects but they use the same package.json)
![image](https://user-images.githubusercontent.com/3356843/208398881-713b0367-9a72-431f-87f4-27a5e45a4661.png)
![image](https://user-images.githubusercontent.com/3356843/208398939-828360c2-e6ce-4639-b6fc-bc7ef25e32be.png)

**Comment by luishcastroc** [comment]
Any timeline for the 3.8 to be released?

**Comment by ice-blaze** [comment]
My project uses angular 14 node 14 and it works like a charm if I use this specific version `3.7.6-dev.master-dcdd391` if I use another version `dev` then the code still work but it builds in ViewEngine instead of ivy.

**Comment by luishcastroc** [comment]
> Any timeline for the 3.8 to be released? 

Just reading that next major angular will completely remove NGCC so more than ever to keep up we need this one :)

**Comment by renatoaraujoc** [comment]
@markwhitfeld a big number of people use your library (because it rocks), any plan the next version? Kinda afraid of being unable to update to `Angular 16`.

**Comment by Sieabah** [comment]
![image](https://user-images.githubusercontent.com/650333/220477488-f15e2091-2fcc-46dc-b1f4-488c6517914d.png)

**Comment by markwhitfeld** [comment]
@renatoaraujoc Thanks for the ping!
Oh my. I had it in my mind that this version was already released!!
Now I remember that there was a TypeScript bug that was blocking the release, and we were waiting for a response on that... then I got very busy. I'll check later today if we are unblocked there and cut the release if we are all good on that front.

**Comment by markwhitfeld** [comment]
Here is the typescript issue which affects static selectors declared on classes and it results in a mysterious runtime error that is difficult to debug: https://github.com/microsoft/TypeScript/issues/52004
If we cut this release, then we are implying that it will run perfectly in the latest version of Angular. But, due to this bug, we know that things will break for some apps. It is not our bug, but it will really adversely affect our users if they upgrade.
A bit of a frustrating situation, because it doesn't seem to be getting much attention from the Typescript team.
I gave a very clear explanation and proposed a solution, but there is radio silence on the issue.

I think that we will have to come up with a way of detecting this situation and giving our users a very specific error message that will assist in diagnosing this issue.

**Comment by luishcastroc** [comment]
> Here is the typescript issue which affects static selectors declared on classes and it results in a mysterious runtime error that is difficult to debug: [microsoft/TypeScript#52004](https://github.com/microsoft/TypeScript/issues/52004) If we cut this release, then we are implying that it will run perfectly in the latest version of Angular. But, due to this bug, we know that things will break for some apps. It is not our bug, but it will really adversely affect our users if they upgrade. A bit of a frustrating situation, because it doesn't seem to be getting much attention from the Typescript team. I gave a very clear explanation and proposed a solution, but there is no response on the issue after more than a month. I will ping a friend that has connections in the Typescript team to see if we can get attention on this.
> 
> I think that we may have to come up with a way of detecting this situation and giving our users a very specific error message that will assist in diagnosing this issue.

Thanks @markwhitfeld this clarifies a lot, and we hope the team can find the best possible solution, Angular 16 Next.0 was released today so Angular is on track to eliminate NGCC for good so that may be (depending on if this can be solved or not) a dealbreaker to update if you're using NGXS which i love :D

**Comment by renatoaraujoc** [comment]
@markwhitfeld how are you doing man? :)

If the library can be rewritten in some way to bypass this TS bug, I believe introducing a breakchange is necessary so people can soon update to NG16. 

Breaking changes happen and are sometimes unavoidable.

Cheers!

**Comment by markwhitfeld** [comment]
Just an update. I received a response on the TS issue, and have now proposed an [alternative solution](https://github.com/microsoft/TypeScript/issues/52004#issuecomment-1460904206).
Hopefully the TS team approves and moves forward with a fix.

It looks like we will have to release ahead of the TS fix though. It will only affect projects targeting ES2022.

**Comment by destus90** [comment]
With ng@15.2.2 `ngxs` stops compiling :/

>./node_modules/@ngxs/store/__ivy_ngcc__/fesm2015/ngxs-store.js:2667:6-17 - Error: export 'ɵivyEnabled' (imported as 'ɵivyEnabled') was not found in '@angular/core'

**Comment by markwhitfeld** [comment]
This issue surfaces when you are compiling with the `tsconfig` specifying a target of `ES2022` or above and you reference the a class from within one of its static initialisers (and the class has a decorator). 
See [this playground](https://www.typescriptlang.org/play?target=8#code/GYVwdgxgLglg9mABDMMoAoIEMA2OCmATgFyIDOUhKA5gDSIQ5ZlkBK+wpAYuNPGAEpEAbwBQiCQwRk4BAHQ441dAAMAkkhRoYuGGSL0yACzggcAE0QAjfIgDkAEmHY8RAL53iK+o2ZsOiABkgQxMLOzAcmBYALb4AgDc4pKE+FAghEi+4RxJbqKioJCwCIjmcABycFBGNOjAYNy8JYIikojJEqnpmYgNeQVFfKUAynBxACL4EHCEWFCz6AKkAMJhZFMzcwuEIp1SYDLyisp2ahVqACqIm7Pzs3aJ+90ZSOhQWITUaaRYYACey0Qf3+iAAvAA+Nr7dozQ6yfAKJToOy3bY0UJ+Yh2egfL5pKKxeJJdrtF69bJkRAAdTmAAc6fhLPgAB5QfBgcxUvHfKAifLtNwDURwo6Ik4osFSm7TJhUMDUUgAeSo1BQuEeSVEAAExpNpncdksRetECqYGrojg9u0KPMYBBEOyKABGcHIVAYOzmy0a+g+9U4J62j6wR3OqAAJndAatJMkdrDTvwFAAzEs2uSkLHcAlEAKE6GHcmKAAWd3lKo1OpDFqIDPCRBZs2qwP54OF+3hlNQACsMdbVoA-HII6WlsLRQikacALTzxAAQWA7N2mzl9oQhhMZksNhp9MZ5mx-sHuEJcSeU+OyJUdgjLrs5B3FmsthzOC8p4tgdHPZdI7RJeSTXuKt73j2kZPsYpivvuH5fi2P5Wn+FCRoBRJXtI04SneEbpgI0EvpYza0lgDJMohH6oVABEYcBIrYTeyh4T246Ec+sEkWkrwHuRR5UWeOA0ex9HEox8LMaoEEUL2RFcW+SG+p+3hKb+Ea9mJiRAA) where this works for ES2021 and [this playground](https://www.typescriptlang.org/play?target=9#code/GYVwdgxgLglg9mABDMMoAoIEMA2OCmATgFyIDOUhKA5gDSIQ5ZlkBK+wpAYuNPGAEpEAbwBQiCQwRk4BAHQ441dAAMAkkhRoYuGGSL0yACzggcAE0QAjfIgDkAEmHY8RAL53iK+o2ZsOiABkgQxMLOzAcmBYALb4AgDc4pKE+FAghEi+4RxJbqKioJCwCIjmcABycFBGNOjAYNy8JYIikojJEqnpmYgNeQVFfKUAynBxACL4EHCEWFCz6AKkAMJhZFMzcwuEIp1SYDLyisp2ahVqACqIm7Pzs3aJ+90ZSOhQWITUaaRYYACey0Qf3+iAAvAA+Nr7dozQ6yfAKJToOy3bY0UJ+Yh2egfL5pKKxeJJdrtF69bJkRAAdTmAAc6fhLPgAB5QfBgcxUvHfKAifLtNwDURwo6Ik4osFSm7TJhUMDUUgAeSo1BQuEeSVEAAExpNpncdksRetECqYGrojg9u0KPMYBBEOyKABGcHIVAYOzmy0a+g+9U4J62j6wR3OqAAJndAatJMkdrDTvwFAAzEs2uSkLHcAlEAKE6GHcmKAAWd3lKo1OpDFqIDPCRBZs2qwP54OF+3hlNQACsMdbVoA-HII6WlsLRQikacALTzxAAQWA7N2mzl9oQhhMZksNhp9MZ5mx-sHuEJcSeU+OyJUdgjLrs5B3FmsthzOC8p4tgdHPZdI7RJeSTXuKt73j2kZPsYpivvuH5fi2P5Wn+FCRoBRJXtI04SneEbpgI0EvpYza0lgDJMohH6oVABEYcBIrYTeyh4T246Ec+sEkWkrwHuRR5UWeOA0ex9HEox8LMaoEEUL2RFcW+SG+p+3hKb+Ea9mJiRAA) where it fails for ES2022.

In particular if you have a state and you use createSelector in the to initialiser for a static property like this:
```TS
@State(/* ..... */)
class MyState {
  static prop = createSelector([MyState], (state: MyModel) => state.prop);
  /* ..... */
}
```
The TS bug causes the `createSelector` call to receive `undefined` instead of `MyState`. This is because the fact that the class has a decorator and the emitted code from TS references a variable before it is initialised for the ES2022 target.

A simple solution to this is to move the selector to another class (that doesn't have a decorator):
```TS
class MyStateSelectors {
  static prop = createSelector([MyState], (state: MyModel) => state.prop);
  /* ..... */
}
```
... or to just export it as a module-level function:
```TS
export myStateProp = createSelector([MyState], (state: MyModel) => state.prop);
```

I would recommend these approaches anyway, so if you are starting out and follow this guidance then it won't affect you.
I have proposed a solution to the TS team that I think will be accepted. I may even do a PR for it ;-)

**Comment by NeedForPerfect** [comment]
class MyStateSelectors {
  static prop = createSelector([MyState], (state: MyModel) => state.prop);
  /* ..... */
}. I've changed selectror and problem still occurs.

**Comment by paulstelzer** [comment]
> With ng@15.2.2 `ngxs` stops compiling :/
> 
> > ./node_modules/@ngxs/store/**ivy_ngcc**/fesm2015/ngxs-store.js:2667:6-17 - Error: export 'ɵivyEnabled' (imported as 'ɵivyEnabled') was not found in '@angular/core'

can confirm, version 3.7.6 of ngxs is not working with angular 15.2.2 (15.2.1 is working).

But the good news: version 3.7.6-dev.master-5f9405c is working with angular 15.2.2

**Comment by neverlose-lv** [comment]
`3.7.6-dev.master-5f9405c`
does not work for me.

```
Build at: 2023-03-16T07:28:16.950Z - Hash: 8725b0f4511cfdee - Time: 15721ms

./src/app/app.module.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Cannot resolve type entity i1.ɵz to symbol

Error: node_modules/@ngxs-labs/actions-executing/lib/actions-executing.module.d.ts:7:89 - error TS2339: Property 'ɵz' does not exist on type 'typeof import("@ngxs/store")'.

7     static ɵmod: i0.ɵɵNgModuleDeclaration<NgxsActionsExecutingModule, never, [typeof i1.ɵz], never>;
                                                                                          ~~


Error: node_modules/@ngxs/router-plugin/src/router.module.d.ts:7:93 - error TS2339: Property 'ɵz' does not exist on type 'typeof import("@ngxs/store")'.

7     static ɵmod: ɵngcc0.ɵɵNgModuleDeclaration<NgxsRouterPluginModule, never, [typeof ɵngcc1.ɵz], never>;
                                                                                              ~~


Error: src/app/app.component.ts:108:18 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(observerOrNext?: Partial<Observer<RouterCancel<unknown, unknown>>> | ((value: RouterCancel<unknown, unknown>) => void) | undefined): Subscription', gave the following error.
    Argument of type '(routerCancel: RouterCancel<RouterState>) => void' is not assignable to parameter of type 'Partial<Observer<RouterCancel<unknown, unknown>>> | ((value: RouterCancel<unknown, unknown>) => void) | undefined'.
      Type '(routerCancel: RouterCancel<RouterState>) => void' is not assignable to type '(value: RouterCancel<unknown, unknown>) => void'.
        Types of parameters 'routerCancel' and 'value' are incompatible.
          Type 'RouterCancel<unknown, unknown>' is not assignable to type 'RouterCancel<RouterState, RouterStateSnapshot>'.
            Type 'unknown' is not assignable to type 'RouterState'.
  Overload 2 of 2, '(next?: ((value: RouterCancel<unknown, unknown>) => void) | null | undefined, error?: ((error: any) => void) | null | undefined, complete?: (() => void) | null | undefined): Subscription', gave the following error.
    Argument of type '(routerCancel: RouterCancel<RouterState>) => void' is not assignable to parameter of type '(value: RouterCancel<unknown, unknown>) => void'.
      Types of parameters 'routerCancel' and 'value' are incompatible.
        Type 'RouterCancel<unknown, unknown>' is not assignable to type 'RouterCancel<RouterState, RouterStateSnapshot>'.

108       .subscribe((routerCancel: RouterCancel<RouterState>) => {
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **


✖ Failed to compile.
```

my *package.json*:

```
{
  "name": "apollo-ng",
  "version": "15.0.1",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test",
    "lint": "ng lint",
    "postinstall": "patch-package"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~15.2.2",
    "@angular/cdk": "~15.2.2",
    "@angular/common": "~15.2.2",
    "@angular/compiler": "~15.2.2",
    "@angular/core": "~15.2.2",
    "@angular/forms": "~15.2.2",
    "@angular/platform-browser": "~15.2.2",
    "@angular/platform-browser-dynamic": "~15.2.2",
    "@angular/router": "~15.2.2",
    "@asymmetrik/ngx-leaflet": "^15.0.1",
    "@auth0/angular-jwt": "^5.1.2",
    "@fullcalendar/angular": "^6.1.4",
    "@fullcalendar/core": "^6.1.4",
    "@fullcalendar/daygrid": "^6.1.4",
    "@fullcalendar/interaction": "^6.1.4",
    "@fullcalendar/timegrid": "^6.1.4",
    "@ngxs-labs/actions-executing": "^1.0.3",
    "@ngxs-labs/immer-adapter": "^3.0.5",
    "@ngxs-labs/select-snapshot": "^4.0.0",
    "@ngxs/devtools-plugin": "^3.7.6",
    "@ngxs/form-plugin": "^3.7.6",
    "@ngxs/logger-plugin": "^3.7.6",
    "@ngxs/router-plugin": "^3.7.6",
    "@ngxs/storage-plugin": "^3.7.6",
    "@ngxs/store": "^3.7.6-dev.master-5f9405c",
    "chart.js": "^4.2.1",
    "i": "^0.3.7",
    "immer": "^9.0.19",
    "leaflet": "^1.9.3",
    "ng2-validation": "^4.2.0",
    "ngxs-reset-plugin": "^3.0.0",
    "npm": "^9.6.2",
    "patch-package": "^6.5.1",
    "primeflex": "^3.3.0",
    "primeicons": "6.0.1",
    "primeng": "15.2.0",
    "quill": "^1.3.7",
    "rxjs": "~7.8.0",
    "tslib": "^2.5.0",
    "web-animations-js": "^2.3.2",
    "zone.js": "~0.13.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^15.2.3",
    "@angular-eslint/builder": "15.2.1",
    "@angular-eslint/eslint-plugin": "15.2.1",
    "@angular-eslint/eslint-plugin-template": "15.2.1",
    "@angular-eslint/schematics": "15.2.1",
    "@angular-eslint/template-parser": "15.2.1",
    "@angular/cli": "~15.2.3",
    "@angular/compiler-cli": "~15.2.2",
    "@types/jasmine": "~4.3.1",
    "@types/leaflet": "^1.9.3",
    "@types/node": "^18.15.3",
    "@typescript-eslint/eslint-plugin": "^5.55.0",
    "@typescript-eslint/parser": "^5.55.0",
    "eslint": "^8.36.0",
    "jasmine-core": "~4.6.0",
    "karma": "~6.4.1",
    "karma-chrome-launcher": "~3.1.1",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "typescript": "4.9.5"
  }
}
```

**Comment by neverlose-lv** [comment]
It seems that NGXS Router plugin and Actions Executing plugin must be updated, too.

**Comment by vojtesaak** [comment]
Same here, still not compiling :(

![Screenshot 2023-03-20 at 16 51 27](https://user-images.githubusercontent.com/5442796/226395005-30398706-2103-4cc9-8794-e7a59a50112d.png)

**Comment by mrs-cp** [comment]
thanks @vojtesaak, tried that, too, however, running npm ci after installing this version then breaks the whole thing again and our gitlab pipelines fail accordingly :(

**Comment by neverlose-lv** [comment]
How long to wait until the fix will be released?

**Comment by JimLixin** [comment]
> ~Same here, still not compiling :(~
> 
> ![Screenshot 2023-03-20 at 16 51 27](https://user-images.githubusercontent.com/5442796/226395005-30398706-2103-4cc9-8794-e7a59a50112d.png)
> 
> EDIT: fixed by updating to:
> 
> ```
> "@ngxs/devtools-plugin": "3.7.6-dev.master-daef739",
> "@ngxs/form-plugin": "3.7.6-dev.master-daef739",
> "@ngxs/router-plugin": "3.7.6-dev.master-daef739",
> "@ngxs/storage-plugin": "3.7.6-dev.master-daef739",
> "@ngxs/store": "3.7.6-dev.master-daef739",
> ```

This version 3.7.6-dev.master-daef739 fixed my build issue as well. Thank you!

**Comment by markwhitfeld** [comment]
Great news! [v3.8.0](https://github.com/ngxs/store/releases/tag/v3.8.0) has been released and it includes a fix for this issue.
We are closing this issue, but please re-open it if the issue is not resolved.
Please leave a comment in the [v3.8.0 release discussion](https://github.com/ngxs/store/discussions/1985) if you come across any regressions with respect to your issue.

**Comment by markwhitfeld** [comment]
For those monitoring this issue, I see that the TypeScript bug fix has been merged and it looks like it will be part of the next minor Typescript release!!! Fantastic news!
