### ISSUE TITLE
ERROR in node_modules/@ngxs/store/src/of-action.d.ts(1,10): error TS2305: Module '"/Users/workspace/git/proj-web/node_modules/rxjs/Rx"' has no exported member 'OperatorFunction'.

### ISSUE THREAD

**Issue by pinalbhatt** [ngxs/store#270]
### Versions

Node: v9.11.1
NPM: 5.8.0
Angular: 5.2.9
Angular-CLI: 1.7.4
NGXS: 3.0.0-rc.0
rxjs: 5.5.8

```
* ngxs:3.0.0-rc.0
* @angular/core:5.2.9
```

### Repro steps

Just added 
```
import { NgxsModule } from '@ngxs/store';
```
in app.module.ts and tried to run ```ng build```

and i get this error:
```
ERROR in node_modules/@ngxs/store/src/of-action.d.ts(1,10): error TS2305: Module '"/Users/workspace/git/proj-web/node_modules/rxjs/Rx"' has no exported member 'OperatorFunction'.
```

**Comment by amcdnl** [comment]
Only works on RX6 and RX 5.5.6

**Comment by pinalbhatt** [comment]
@amcdnl  i am getting this error even after changing rxjs to 5.5.6.  ("rxjs": "5.5.6")

**Comment by pinalbhatt** [comment]
thanks @amcdnl  that worked.

**Comment by Dercetech** [comment]
Hi @amcdnl,
Pardon my nitpicking here, but when checking out your [demo stackblitz](https://stackblitz.com/edit/ngxs-simple) I see it's still running rxjs 5.5.2.
Has this changed since @ngxs/store 3.0.0-beta.0 ? 
Another discussion pointed to using NG 6 & RX 6. Not possible in an Ionic 3.x environment, hence my nitpicking :-)
