### ISSUE TITLE
📚[DOCS]: Example of upsertItem invalid for ngxs 3.8.1

### ISSUE THREAD

**Issue by jase88** [ngxs/store#2027]
### Description

The [page "State Operators" in the docs](https://www.ngxs.io/snippets/operators#state-operator-code) gives a code snippet for the method `upsertItem`.

This code has TypeScript errors for the latest 3.8.1 version. Seeing this after updating from 3.7.6 (where it compiled fine).

## 🔬 Minimal Reproduction
- copy the given function from the docs to a project using ngxs 3.8.1

### What's the affected URL?**
https://www.ngxs.io/snippets/operators#state-operator-code

### Expected vs Actual Behavior**

Expected: The docs should (also) work for the latest ngxs version
Actual: TypeScript error is thrown if trying to compile 

## 🔥 Exception or Error
<pre><code>

Error: src/upsert.ts:1:27 - error TS2307: Cannot find module '@ngxs/store/operators/internals' or its corresponding type declarations.

1 import { Predicate } from '@ngxs/store/operators/internals';
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: src/upsert.ts:16:40 - error TS2345: Argument of type 'T' is not assignable to parameter of type 'NoInfer<T>'.

16         <StateOperator<T[]>>insertItem(upsertValue, <number>selector)
                                          ~~~~~~~~~~~


Error: src/upsert.ts:23:40 - error TS2345: Argument of type 'T' is not assignable to parameter of type 'NoInfer<T>'.

23         <StateOperator<T[]>>insertItem(upsertValue)
                                          ~~~~~~~~~~~
</code></pre>
